service: journal-web-user-service

custom:
  tableName: "users-table-${self:provider.stage}"

provider:
  name: aws
  architecture: x86_64
  runtime: nodejs18.x
  stage: prod
  region: ap-south-1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
